basePath: /v1
definitions:
  models.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  models.ResponseOK:
    properties:
      message:
        type: string
    type: object
info:
  contact: {}
  description: This is upload and get products api.
  title: Swagger for blog api
  version: "1.0"
paths:
  /create-file:
    post:
      consumes:
      - application/json
      description: File upload
      parameters:
      - description: File
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ResponseOK'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: File upload
      tags:
      - file-upload
swagger: "2.0"
